import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 p-5 flex gap-5">
        <Link href="/">Home Page</Link>
        <Link href="/blog">Blog</Link>
        <Link href="/dashboard">Dashboard</Link>
        <Link href="/dashboard/customers">Customers</Link>
        <Link href="/settings">Settings</Link>
        <Link href="/team">Team</Link>
        <Link href="/teamdetail">Team Detail</Link>

        </header>
        {children}
      </body>
    </html>
  );
}
